name: big_decimal
description: Numeric library to manipulate very big numbers keeping very high precision.
version: 0.0.1
repository: https://github.com/ciripel/big_decimal

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  decimal: ^2.3.0
  equatable: ^2.0.5
  intl: ^0.17.0
